### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dslvd** [Spiderjockey02/Discord-Bot#196]
I have an error, is this because of an old node.js version?
```
/home/runner/Discord-Bot-1/src/utils/EgglordEmbed.js:14
        const language = this.guild?.settings.Language ?? this.bot.config.defaultSettings.Language;
                                    ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/Discord-Bot-1/src/utils/index.js:2:9)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by Spiderjockey02** [comment]
Before trying to use the bot please use the installation guide. (You need node v14 or higher to run this bot)
