### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by Cyber-Pop** [Spiderjockey02/Discord-Bot#20]
I filled out all the values in config.js and did all the things. I am getting an error -
```
Error: MANAGER_DESTROYED
    at WebSocketManager.destroy (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:333:54)
    at Client.destroy (/home/container/node_modules/discord.js/src/client/Client.js:236:13)
    at Client.login (/home/container/node_modules/discord.js/src/client/Client.js:225:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) 
```
i am not sure what's the issue

**Comment by Spiderjockey02** [comment]
user fixed via discord.
