### ISSUE TITLE
ERROR Please fix your errors before loading the bot.

### ISSUE THREAD

**Issue by cerfox** [Spiderjockey02/Discord-Bot#224]
```
$ node .
[21:51:01:150]: LOG =-=-=-=-=-=-=- Config file Verification -=-=-=-=-=-=-=
[21:51:01:150]: LOG Verifying config..
[21:51:02:353]: LOG ✗ Twitch API key is missing.
Error: Invalid authentication credentials
    at Client.user (C:\Discord-Bot\node_modules\fortnite\src\Client.js:40:70)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.module.exports.run (C:\Discord-Bot\src\scripts\verify-config.js:71:3)
    at async C:\Discord-Bot\src\index.js:7:24
[21:51:02:697]: LOG ✗ Fortnite API key is incorrect.
[21:51:03:697]: LOG ✗ Ksoft API key is incorrect.
[21:51:03:697]: ERROR Please fix your errors before loading the bot.
```

**Comment by Spiderjockey02** [comment]
All API's are optional so if you don't want to use a particular API just leave the value as an empty string. (`''`)

**Comment by cerfox** [comment]
i already leave the string empty sir, but the bot still doesn't want to run :( ( sorry for my bad english sir )

**Comment by cerfox** [comment]
![Screenshot_478](https://user-images.githubusercontent.com/88929256/131256281-c8cca9a2-4fed-47b7-8206-d72a44c0ba29.png)

**Comment by Spiderjockey02** [comment]
I'm talking about the ksoft & fortnight as it says incorrect API instead of missing API.

**Comment by cerfox** [comment]
![Screenshot_479](https://user-images.githubusercontent.com/88929256/131256485-be8d8cc4-7508-4574-976e-68b6b30be582.png)

when i remove all api string to empty, its stuck on that proccess

**Comment by cerfox** [comment]
fixed. thankyou sir :D
