### ISSUE TITLE
Unhandled promise rejection: Cannot send an empty message.

### ISSUE THREAD

**Issue by vSilva-gb** [Spiderjockey02/Discord-Bot#232]
I'm getting this error after using the para-view command, I've added a playlist all right, but I can't see what songs it contains.
![Screenshot_3](https://user-images.githubusercontent.com/41455280/132139722-ab69cb08-28a6-4fcc-907d-49fdd6356694.png)

```
[19:44:54:943]: ERROR Unhandled promise rejection: Cannot send an empty message.
DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (/home/node/bot/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/node/bot/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async TextChannel.send (/home/node/bot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:171:15) {
  method: 'post',
  path: '/channels/769304180095451166/messages',
  code: 50006,
  httpStatus: 400,
  requestData: {
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}
```

**Comment by Spiderjockey02** [comment]
This issue should be fixed now. This page will close in a couple hours, just in case more errors are found
