### ISSUE TITLE
HELP ME!!!

### ISSUE THREAD

**Issue by TacsiDavid** [Spiderjockey02/Discord-Bot#238]
C:\Users\ifoxy\Desktop\Bot\Lavalink>java -jar Lavalink.jar
2021-09-07 12:33:53.915  WARN 9404 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2021-09-07 12:33:54.050 ERROR 9404 --- [           main] lavalink.server.Launcher                 : Application failed

java.lang.UnsupportedClassVersionError: lavalink/server/info/AppInfo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_301]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[na:1.8.0_301]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[na:1.8.0_301]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[na:1.8.0_301]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[na:1.8.0_301]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_301]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_301]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_301]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.8.0_301]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_301]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[Lavalink.jar:na]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_301]
        at lavalink.server.Launcher.getVersionInfo(Launcher.kt:51) ~[classes!/:na]
        at lavalink.server.Launcher.getVersionInfo$default(Launcher.kt:50) ~[classes!/:na]
        at lavalink.server.Launcher.main$lambda-3(Launcher.kt:123) ~[classes!/:na]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82) ~[spring-boot-2.5.0.jar!/:2.5.0]
        at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63) ~[spring-boot-2.5.0.jar!/:2.5.0]
        at java.util.ArrayList.forEach(Unknown Source) ~[na:1.8.0_301]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.5.0.jar!/:2.5.0]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.5.0.jar!/:2.5.0]
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62) ~[spring-boot-2.5.0.jar!/:2.5.0]
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:373) ~[spring-boot-2.5.0.jar!/:2.5.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:331) ~[spring-boot-2.5.0.jar!/:2.5.0]
        at lavalink.server.Launcher.main(Launcher.kt:129) ~[classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_301]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_301]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_301]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_301]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[Lavalink.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[Lavalink.jar:na]

2021-09-07 12:33:54.445 ERROR 9404 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.UnsupportedClassVersionError: lavalink/server/info/AppInfo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_301]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[na:1.8.0_301]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[na:1.8.0_301]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[na:1.8.0_301]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[na:1.8.0_301]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_301]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_301]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_301]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.8.0_301]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_301]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[Lavalink.jar:na]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_301]
        at lavalink.server.Launcher.getVersionInfo(Launcher.kt:51) [classes!/:na]
        at lavalink.server.Launcher.getVersionInfo$default(Launcher.kt:50) [classes!/:na]
        at lavalink.server.Launcher.main$lambda-3(Launcher.kt:123) [classes!/:na]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82) ~[spring-boot-2.5.0.jar!/:2.5.0]
        at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63) ~[spring-boot-2.5.0.jar!/:2.5.0]
        at java.util.ArrayList.forEach(Unknown Source) ~[na:1.8.0_301]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.5.0.jar!/:2.5.0]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.5.0.jar!/:2.5.0]
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62) ~[spring-boot-2.5.0.jar!/:2.5.0]
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:373) ~[spring-boot-2.5.0.jar!/:2.5.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:331) ~[spring-boot-2.5.0.jar!/:2.5.0]
        at lavalink.server.Launcher.main(Launcher.kt:129) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_301]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_301]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_301]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_301]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [Lavalink.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [Lavalink.jar:na]

C:\Users\ifoxy\Desktop\Bot\Lavalink>pause
Press any key to continue . . .

**Comment by Spiderjockey02** [comment]
You need to install java 11 (you have 8 currently)
