### ISSUE TITLE
Lavalink isnt working

### ISSUE THREAD

**Issue by pxsx** [Spiderjockey02/Discord-Bot#539]
Lavalink node: 'narco.buses.rocks', has error: 'Unexpected op "ready" with data: [object Object]'. 

Lavalink isnt working am did all like in the setup guide

**Comment by Spiderjockey02** [comment]
Yes it is an error, but could you try playing some music. As I have noticed with the newer lavalink server it does display this error but still continues to play and use effects

**Comment by pxsx** [comment]
now i get this error

Cannot read properties of undefined (reading 'conf')
    at SlashCreate.run (/home/container/src/events/custom/slashCreate.js:35:28)
    at Egglord.<anonymous> (/home/container/src/bot.js:71:38)
    at Egglord.emit (node:events:513:28)
    at InteractionCreate.run (/home/container/src/events/bot/interactionCreate.js:34:43)
    at Egglord.<anonymous> (/home/container/src/bot.js:71:38)
    at Egglord.emit (node:events:513:28)
    at InteractionCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:494:22)
    
    
    
    and i turned on PRESENCE INTENT, SERVER MEMBERS INTENT and MESSAGE CONTENT INTENT

**Comment by Spiderjockey02** [comment]
What command did u run, cuz I don't see how that's possible?

**Comment by pxsx** [comment]
i tried the meme command but it doenst show in the slash command menu
because the bot didnt created them

**Comment by Spiderjockey02** [comment]
yes as you need to go on the server that u assigned as the SupportServer in the config and run `/reload misc feature:interactions`

**Comment by pxsx** [comment]
ahhh okay good to know thanks
