### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by jewelalex** [Spiderjockey02/Discord-Bot#97]
hello sir,

i get this error 

08:13:20]: READY Mongoose connection successfully opened
/root/prottoy/node_modules/mongodb/lib/cmap/connection.js:268
          callback(new MongoError(document));
                   ^

MongoError: not authorized on prottoy to execute command { find: "giveaways", filter: {}, projection: {}, returnKey: false, showRecordId: false }
    at MessageStream.messageHandler (/root/prottoy/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (node:events:378:20)
    at processIncomingData (/root/prottoy/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/root/prottoy/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (node:internal/streams/writable:400:12)
    at _write (node:internal/streams/writable:341:10)
    at MessageStream.Writable.write (node:internal/streams/writable:345:10)
    at Socket.ondata (node:internal/streams/readable:750:22)
    at Socket.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  ok: 0,
  code: 13
}

thx

**Comment by jewelalex** [comment]
plzzzzz help me sir

**Comment by Spiderjockey02** [comment]
That's not an error with the code but an error with you database.

**Comment by idkwhattoputhere121** [comment]
Yeah.

**Comment by jewelalex** [comment]
this error im getthing now 



[12:46:29]: ERROR Privileged intent provided is not enabled or whitelisted. 
(node:16033) UnhandledPromiseRejectionWarning: Error [SHARDING_READY_TIMEOUT]: Shard 0's Client took too long to become ready.
    at Timeout.onTimeout (/root/prottoy/node_modules/discord.js/src/sharding/Shard.js:163:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16033) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16033) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Spiderjockey02** [comment]
U need to go the discord developers page and enable both privileged intents for your bot.

**Comment by jewelalex** [comment]
now getthing this error

[23:51:14]: ERROR Node: 'localhost', has error: 'connect ECONNREFUSED 127.0.0.1:2333'. 
MongoError: command insert requires authentication
    at MessageStream.messageHandler (/root/prottoy/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:314:20)
    at processIncomingData (/root/prottoy/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/root/prottoy/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at MessageStream.Writable.write (_stream_writable.js:318:11)
    at Socket.ondata (_stream_readable.js:718:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  ok: 0,
  code: 13,
  codeName: 'Unauthorized'
}
[23:51:44]: ERROR Node: 'localhost', has error: 'connect ECONNREFUSED 127.0.0.1:2333'. 
[23:52:14]: ERROR Node: 'localhost', has error: 'connect ECONNREFUSED 127.0.0.1:2333'.

idk what to do plz help ........ im using centos 7 with mongodb 
if you help me maybe to setup mongodb currectly for your code will be great 

thx

**Comment by DynamoYT** [comment]
@jewelalex You didn't turn on the [Lavalink](https://github.com/Frederikam/Lavalink) server. that's why you are getting the error `ERROR Node: 'localhost', has error: 'connect ECONNREFUSED 127.0.0.1:2333'.`

**Comment by SpaceLeft** [comment]
> @jewelalex You didn't turn on the [Lavalink](https://github.com/Frederikam/Lavalink) server. that's why you are getting the error `ERROR Node: 'localhost', has error: 'connect ECONNREFUSED 127.0.0.1:2333'.`

u need connect with lavalink

**Comment by jewelalex** [comment]
ok sir for turn on Lavalink what should i do like which command i have to use

**Comment by DynamoYT** [comment]
> ok sir for turn on Lavalink what should i do like which command i have to use

Watch this from 0:32
https://youtu.be/KxDPk9-bME0

**Comment by jewelalex** [comment]
@DynamoYT i added u on discord accept me plz

**Comment by Spiderjockey02** [comment]
This has been closed as it appears to be user error. If an error still occurs join the support server in the description.
